docs/_layouts/page.html
docs/css/fui-site.css
docs/pages/fundamentals/type.html
docs/scss/_docs-headers.scss
docs/scss/_docs-type.scss

#50
corrected only the issues that had a high impact. some of the items are too specific which would require custom styling for the page and utilize the lib or docs site spacing, margins etc.

#50 update type page based on design feedback.

---

scss/layout/app.scss

#150 remove leftnav hover

---

ops/misc/src-component.scss

Update create component template file

---

scss/_settings.scss
scss/components/_mixins.scss
scss/components/button.scss
scss/components/card.scss
scss/components/pagination.scss
scss/components/tabs.scss
scss/core/elements.scss
scss/icons/_mixins.scss
scss/icons/_settings.scss
scss/icons/icon.scss
scss/theme/dark.scss
scss/theme/fundamental.scss
test/templates/button/component.njk
test/templates/button/data.json
test/templates/button/index.njk

This — along with the icons updates — breaks a lot of the components (and pages) that use buttons. Those can be fixed one by one with the individual components.
> NOTE: This does change a lot with the buttons. It simplifies the classes considerably and changes the button types.
You no longer need the base class when using a modifier and the icon class can be added directly to the button with no extra container required.
```
<button class="fd-button--main">Button</button>
<button class="fd-button--main sap-icon--cart">Add to Cart</button>
```
|Type|Class|Alt|
|--|--|--|
|Default|`.fd-button`|`fd-button--positive`, `fd-button--negative`|
|Main|`.fd-button--main`|`fd-button--positive`, `fd-button--negative`|
|Secondary|`.fd-button--secondary`||
|Toolbar|`.fd-button--toolbar`||
|Type|Class| …

#189 implements new button types and sizes

---

scss/components/tabs.scss
test/templates/tabs/index.njk

#208  
Minor updates to match https://zpl.io/a8Wz66g
> Opened #220 to deal with overflow menu later on

#208 updates tabs to mds

---

scss/components/nav.scss
test/templates/nav/index.njk

#205 
Minor updates to spacing. This is a minor utility component useful for compositing lists in other components.

#205 updates nav

---

scss/components/_mixins.scss
scss/components/link.scss
scss/components/pagination.scss
test/templates/pagination/component.njk

#206 
Markup changed to simplify.

#206 updates pagination

---

scss/components/badge.scss
scss/components/label.scss
test/templates/badge/index.njk

#187 
Adds new `--filled` variant to the badge

#187 updates badge and label, adds filled variant

---

scss/components/table.scss
test/templates/table/component.njk
test/templates/table/index.njk

#207 
Primarily color and spacing updates.

#207 updates table styles

---

scss/components/tree.scss
test/templates/tree/component.njk

#210 
Primarily style changes, colors and such.

#210 updates tree

---

scss/components/list-group.scss
test/templates/list-group/component.njk
test/templates/list-group/data.json

#203 
Primarily style change except for the button in the `actions` container follows the new syntax.

#203 updates list group

---

scss/components/_mixins.scss
scss/core/elements.scss

#233 removes globak visited state

---

scss/_settings.scss
scss/core/root.scss
test/templates/identifier/index.njk
test/templates/pages/styles.njk

#234 updates accent colors

---

docs/_data/sidebars/left-navigation-sidebar.yml
docs/pages/components/breadcrumb.md

#180 
page - http://localhost:4000/components/breadcrumb.html
component - http://localhost:3030/breadcrumb#

#180 breadcrumb documentation

---

docs/pages/components/card.md
test/templates/card/index.njk

#270 
page - http://localhost:4000/components/card.html
component - http://localhost:3030/card

#270 card markup updates

---

docs/css/fui-site.css
docs/pages/components/button.md
docs/scss/_docs-display-component.scss

#268 
page - http://localhost:4000/components/button.html#standard-button
component - http://localhost:3030/button

#268 buttons markup and documentation updates

---

docs/_data/sidebars/left-navigation-sidebar.yml
docs/pages/components/inline-help.md

#293 
page - http://localhost:4000/components/inline-help.html
component - http://localhost:3030/inline-help

#293 added inline-help documentation

---

docs/pages/components/image.md

#291 
page - http://localhost:4000/components/image.html
component - http://localhost:3030/image

#291 update image documentation

---

docs/css/customstyles.css
docs/css/fui-site.css
docs/pages/components/icons.md
docs/scss/_docs-icons.scss
docs/scss/docs-all.scss

#289 
page - http://localhost:4000/components/icons.html
component - http://localhost:3030/icon

#289 icons grid adjustments

---

docs/_data/sidebars/left-navigation-sidebar.yml
docs/pages/components/link.md

#295 
page - http://localhost:4000/components/link.html
component - http://localhost:3030/link

#295 added link documentation

---

scss/components/toggle.scss

#280 
http://localhost:3030/toggle

#280 Fixes alignment on Toggles

---

scss/components/button.scss

#237 
http://localhost:3030/button
To get it *perfect* will likely need to treat the icons that appear in the buttons on a case by case scenario. Some seem to be designed 1-2px lower at times on the grid they were designed on in the font compared to others.

#237 First pass at better alignment in buttons / buttons with icons.

---

docs/_data/sidebars/left-navigation-sidebar.yml
docs/pages/components/button.md
docs/pages/components/list-group.md

#303 
page - http://localhost:4000/components/list-group.html
component - http://localhost:3030/list-group

#303 update list group markup and documentation

---

docs/_data/sidebars/left-navigation-sidebar.yml
docs/css/fui-site.css
docs/pages/components/side-navigation.md
docs/scss/_docs-display-component.scss
test/templates/side-nav/component.njk
test/templates/side-nav/index.njk

#182 
http://localhost:3030/side-nav#
http://localhost:4000/components/side-navigation.html

#182 Docs: side nav 

---

docs/_data/sidebars/left-navigation-sidebar.yml
docs/pages/components/mega-menu.md

#305 
http://localhost:4000/components/mega-menu.html
http://localhost:3030/mega-menu#

Docs: Mega menu 

---

docs/css/fui-site.css
docs/pages/components/dropdown.md
docs/pages/layouts/global-navigation.md
docs/scss/_docs-display-component.scss
docs/scss/_docs-example.scss

#327
http://localhost:3030/dropdown
http://localhost:4000/components/dropdown.html
http://localhost:3030/global-nav
http://localhost:4000/layouts/global-navigation.html

#327 dropdown documentation + global nav component fix

---

docs/pages/components/pagination.md

#331 
http://localhost:3030/pagination
http://localhost:4000/components/pagination.html

#331 update pagination markup

---

docs/pages/components/tree.md

#407 
http://localhost:4000/components/tree.html

#407 tree copy + markup formatting updates

---

docs/pages/components/toggle.md

#405 
http://localhost:4000/components/toggle.html

#405 toggle copy update

---

docs/pages/components/tag.md

#402 
http://localhost:4000/components/tag.html

#402 tag copy updates

---

docs/pages/components/tabs.md

#403
http://localhost:4000/components/tabs.html

#403 tabs copy update

---

docs/pages/components/table.md

#400 
http://localhost:4000/components/table.html

#400 table copy updates

---

docs/pages/components/pagination.md

#399 
http://localhost:4000/components/pagination.html

#399 pagination copy updates

---

docs/pages/components/modal.md

#398 
http://localhost:4000/components/modal.html

#398 modal copy updates

---

scss/components/form.scss

#416 Adds * after required labels

---

docs/pages/components/mega-menu.md

#397 
http://localhost:4000/components/mega-menu.html

#397 mega menu copy update

---

docs/pages/components/loading-spinner.md

#396 
http://localhost:4000/components/loading-spinner.html

#396 loading spinner copy updates

---

docs/pages/components/identifier.md

#393 
http://localhost:4000/components/identifier.html

#393 identifier copy updates

---

docs/pages/components/form.md

#378 
https://github.com/SAP/fundamental/issues/378

#378 form copy updates

---

docs/pages/components/dropdown.md

#377 
http://localhost:4000/components/dropdown.html

#377 dropdown copy update

---

docs/pages/components/contextual-menu.md

#376 
http://localhost:4000/components/contextual-menu.html

#376 contextual menu copy update

---

docs/pages/components/breadcrumb.md

#375 
http://localhost:4000/components/breadcrumb.html

#375 breadcrumb copy updates

---

package-lock.json
package.json

@saadmhybris Is that `.lock` file OK?
I updated to the newest version of node and needed to update this package. Please test and see if this **requires** greater node version before merging.

#469 bump node-sass to v4.9.0

---

docs/_includes/demo-page-components/table-page-content.html
test/templates/layout/component.njk
test/templates/pages/panel.njk
test/templates/panel/component.njk

#245 
Click filter button to toggle 
http://localhost:3030/pages/panel
http://localhost:4000/demo-pages/table-demo-page.html

#245 Lib: add js to filter button in panels

---

docs/_layouts/component.njk
docs/_layouts/default.html
docs/index.html
docs/js/search.json

#473 
Fixed search.json which was being parsed as an html file which in turn was breaking the search. no need to update the plugin.

#473 fix search

---

scss/layout/panel.scss
test/templates/layout/component.njk
test/templates/pages/panel.njk
test/templates/panel/component.njk
test/templates/panel/index.njk

#463 
added support for description panels. 
http://localhost:3030/pages/panel

#463 add description to panels

---

scss/components/form.scss

#443 
http://localhost:3030/form

#443 reduce space between form-items and check items and label

---

scss/components/form.scss

#488 
http://localhost:3030/form

#408: zero out margin-bottom on small screens only.

---

scss/components/tabs.scss

#503 
http://localhost:3030/tabs
design - https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/screen/5ac33d7bf3d7be96b0025c04

#503 links color updates

---

scss/components/button.scss
test/templates/button/index.njk

#496
http://localhost:3030/button
http://localhost:3030/button-group

#496 button updates 

---

scss/components/action-bar.scss
test/templates/action-bar/component.njk
test/templates/action-bar/index.njk
test/templates/contextual-menu/index.njk

#365 
http://localhost:3030/action-bar

#365 action bar responsiveness

---

scss/components/input-group.scss
test/templates/input-group/component.njk

#464 
http://localhost:3030/input-group
https://zpl.io/V18onzQ

#464 input-group number spinner update

---

scss/components/calendar.scss

#500 Bug: Calendar

---

scss/components/popover.scss
scss/components/time-picker.scss
scss/components/time.scss
test/templates/index.njk
test/templates/time-picker/component.njk
test/templates/time-picker/data.json
test/templates/time-picker/index.njk
test/templates/time/component.njk
test/templates/time/data.json
test/templates/time/index.njk

#439 
#385 
For `time-picker` I need to mock up a similar "control" that date-picker has with an input group. Also, disabled states.

#439 time component & #385 time-picker component

---

scss/components/button.scss
test/templates/button/index.njk

Closes sap/fundamental#496
added hover and down states to action buttons 
* http://localhost:3030/button
**Changed**
* action button - added hover and down states

#496 added hover and down states

---

docs/_data/sidebars/left-navigation-sidebar.yml
docs/pages/components/badge-and-label.md

Closes sap/fundamental#462
Status indicator documentation 
* http://localhost:4000/components/badge-label-status.html
**New**
* status indicator documentation 
**Changed**
* nothing 
**Removed**
* nothing

#462 status indicators documentation

---

docs/pages/components/toggle.md

Closes sap/fundamental#559
Toggle documentation update 
* http://localhost:4000/components/toggle.html
**New**
* nothing 
**Changed**
* toggle markup
**Removed**
* nothing

#599 toggle documentation update

---

scss/theme/ariba/_settings.scss
scss/theme/ariba/components/button.scss
scss/theme/ariba/components/toggle.scss

- Add Ariba theme Colors and Theme configuration & Settings.
- Add Standard & Toggle buttons with size and type variation.
* Using documentation
**New**
* Add Ariba theme Settings for color and other config.
* Add Standard button & toggle button theme overrides.
**Changed**
* None
**Removed**
* None

Add Ariba Theme settings & Buttons Updates

---

scss/theme/ariba/components/spinner.scss

Add Circular Spinner for Ariba Theme
* using documentation and variation examples.
**New**
* Add new Circular spinner component
**Changed**
* None
**Removed**
* None

Add Theme Ariba Spinner

---

docs/pages/components/time-picker.md
scss/_settings.scss
test/templates/time-picker/component.njk

add input[type=time] to $fd-elements-inputs--text

---

docs/pages/themes/ariba/form.md
docs/pages/themes/ariba/icon.md
docs/pages/themes/ariba/input-group.md
docs/pages/themes/ariba/loading-spinner.md
docs/pages/themes/ariba/toggle.md

- Update documentation add reference path support for relative path links.
* Using documentation + Gulp Task
**New**
* None
**Changed**
* add reference path support for relative path links.
**Removed**
* None

Update Ariba documentation.

---

scss/theme/ariba/_settings.scss
scss/theme/ariba/components.scss
scss/theme/ariba/components/alert.scss
scss/theme/ariba/components/dropdown.scss
scss/theme/ariba/components/modal.scss

- Add Alert Support with RTL
- Add Dropdow Support with RTL
- Add Modal Support with RTL
- Update component file to include new components
* Docmentation & Examples
**New**
* SCSS for Alert
* SCSS for Modal
* SCSS for dropdown
**Changed**
* Add new file to component bundle
**Removed**
* none

Update Ariba-Theme Add Additonal component support

---

scss/theme/ariba/components/button-group.scss
scss/theme/ariba/components/button.scss
scss/theme/ariba/components/input-group.scss
scss/theme/ariba/components/spinner.scss
scss/theme/ariba/components/toggle.scss

- Fix issue due to leak in encapsulation due to "@at-root" annotation for buttons.
- Fix Input-group issue for large size.
* Docmentation & examples
**New**
* None
**Changed**
* Button SCSS
* Button-Group SCSS
* Input-Group SCSS
* Spinner SCSS
* Toggle SCSS
**Removed**
* None

Update Ariba-Theme fix Button & Form CSS issues.

---

scss/theme/ariba/components/form.scss

- Fix issue due to leak in encapsulation due to "@at-root" annotation for form elements.
- Add RTL support
- Add Semantic support for error & warnings in Input-element.
* Documentation & Examples
**New**
* None
**Changed**
* form SCSS
**Removed**
* None

Update Ariba-Theme fix issues, add semantic & RTL support.

---

docs/pages/themes/ariba/button.md
docs/pages/themes/ariba/form.md
docs/pages/themes/ariba/input-group.md
docs/pages/themes/ariba/loading-spinner.md
docs/pages/themes/ariba/toggle.md

Update Components detail add example and Support for RTL simulation.
* By documentation Look & Feel
**New**
* None
**Changed**
* Pages for Button, Input-group, Spinner, toggle and form elements.
**Removed**
* None

Update Documentation add support RTL Simulation.

---

docs/_data/sidebars/left-navigation-sidebar.yml
docs/_data/themes/ariba/components.yml
docs/pages/themes/ariba/alert.md
docs/pages/themes/ariba/dropdown.md
docs/pages/themes/ariba/modal.md

Add documentation for new components under Ariba-Theme; Alert, Dropdown & Modal with RTL simulation.
* By documentation Look & Feel.
**New**
* Alert Page
* Dropdown Page
* Modal Page
**Changed**
* Side-Navigation for ariba-theme
**Removed**

Update documentation add pages for Alert, Dropdown & Modal.

---

scss/components/dropdown.scss
test/templates/dropdown/index.njk

Closes sap/fundamental#606
fixed width so that is will take the label width. also adjusted heights for various sizes. 
* http://localhost:3030/dropdown
**New**
nothing 
**Changed**
* dropdown
**Removed**
nothing

#606 dropdown width and height fix

---

docs/pages/components/table.md

Closes sap/fundamental#664
table documentation updates
* http://localhost:4000/components/table.html
**New**
* nothing 
**Changed**
* table documentation 
**Removed**
* nothing

#664 table documentation updates

---

docs/pages/components/contextual-menu.md

Closes sap/fundamental#569
update context menu docs
* http://localhost:4000/components/contextual-menu.html
**New**
nothing 
**Changed**
* context menu docs
**Removed**
nothing

#569 update context menu docs

---

README.md

Closes sap/fundamental#698
Update readme.md with project prerequisite.

#698 update readme with project prerequisite

---

docs/pages/components/button.md
docs/pages/components/combobox-input.md
docs/pages/components/date-picker.md
docs/pages/components/form.md
docs/pages/components/input-group.md
docs/pages/components/localization-editor.md
docs/pages/components/multi-input.md
docs/pages/components/search-input.md
docs/pages/components/time-picker.md

Closes sap/fundamental#786 
Documents `--compact` mode for all componnets that support this mode. 
* http://localhost:4000/components/button.html
* http://localhost:4000/components/input-group.html
* http://localhost:4000/components/form.html
* http://localhost:4000/components/combobox-input.html
* http://localhost:4000/components/date-picker.html
* http://localhost:4000/components/localization-editor.html
* http://localhost:4000/components/multi-input.html
* http://localhost:4000/components/search-input.html
* http://localhost:4000/components/time-picker.html
* http://localhost:4000/components/dropdown.html
**Changed**
* http://localhost:4000/components/button.html
* http://localhost:4000/components/input-group.html
* http://localhost:4000/components/form.html
* …

#786 Document new form and button metrics

---

scss/components/button.scss

Closes sap/fundamental# https://github.com/SAP/fundamental/issues/852
Updating vertical-alignment of text in button with icons.
* http://localhost:3030/button
**New**
* Updated vertical alignment:

Aligning buttons with icon and text correctly.

---

docs/pages/components/popover.md

Closes sap/fundamental#872 
* Added examples to show `--left`, `--right` and `no-arrow` modifiers 
* Added examples utitizing various components for `fd-popover__control` 
* http://localhost:4000/components/popover.html
**New**
nothing 
**Changed**
* Popover documentation 
**Removed**
nothing

#872 update popover documentation

---

.github/ISSUE_TEMPLATE.md
README.md
docs/pages/foundation/colors.html
docs/pages/foundation/getting-started-designers.html
docs/pages/foundation/grid.html
docs/pages/foundation/index.md
docs/pages/guides/design-system-utilities.md
docs/pages/guides/how-to-use-scss.md
docs/pages/layouts/index.md
test/templates/pages/layouts/starter.njk

#900 Fundamental UI to Fiori Fundamentals

---

package-lock.json

Closes sap/fundamental#918
* go to repo [homepage](https://github.com/SAP/fundamental)
**Changed**
* `deep-extend` and `mixin-deep` version updated in package-lock.json

#918 fix security warnings 

---

docs/js/customscripts.js
docs/pages/components/form.md
scss/core/forms.scss

Closes sap/fundamental# https://github.com/SAP/fundamental/issues/797
Added indetrminate state to the checkbox
http://localhost:4000/components/form.html
**New**
Addition on Indeterminate state of the checkbox

Feature/Add indeterminate state on checkboxes -#797

---

docs/pages/components/table.md
scss/components/table.scss
test/templates/table/component.njk
test/templates/table/index.njk

Closes sap/fundamental#https://github.com/SAP/fundamental/issues/807
Add the row highlights to the tables
http://localhost:4000/components/table.html
http://localhost:4000/components/table.html
Added the new property and class for option for user to highlight table rows
**Changed**
**Removed**

Feature/add remover lines in tables-#807

---

netlify.toml

Inadvertently committed an update to this file directly to develop
**New**
**Changed**
**Removed**

Fix netlify deployment

---

scss/components.scss
scss/components/product-menu.scss
scss/components/shellbar.scss
test/templates/breadcrumb/index.njk
test/templates/pages/layouts/shell.njk
test/templates/pages/shell.njk
test/templates/product-menu/component.njk
test/templates/product-menu/data.json
test/templates/product-menu/index.njk
test/templates/shellbar/component.njk
test/templates/shellbar/index.njk

Bring back the `product-menu`!

Product menu

---

docs/_includes/demo-page-components/app-sidebar-content.html
docs/_includes/demo-page-components/modal-app-overlay.html
docs/pages/components/modal.md
test/templates/modal/index.njk
test/templates/pages/layouts/shell.njk
test/templates/pages/modal-placement.njk

Closes sap/fundamental#https://github.com/SAP/fundamental/issues/840
Updated the action placement on Modal and demo pages
http://localhost:4000/components/modal.html
http://localhost:4000/demo-pages/sidebar-app-demo.html
http://localhost:4000/demo-pages/modal-overlay-demo-page.html
http://localhost:4000/demo-pages/alert-overlay-demo-page.html
http://localhost:3030/modal
http://localhost:3030/pages/modal-placement
http://localhost:3030/pages/app/sidebar

update action placement docs and Lib-#840

---

docs/_data/components.yml
docs/_data/sidebars/left-navigation-sidebar.yml
docs/pages/components/dialog.md
scss/components.scss
scss/components/dialog.scss
test/templates/dialog/component.njk
test/templates/dialog/data.json
test/templates/dialog/index.njk
test/templates/index.njk

Closes sap/fundamental#977
Added the new Dialog Control
http://localhost:3030/dialog
http://localhost:4000/components/dialog.html
**New**
New Dialog Component

Feature/Add dialog #977

---

docs/pages/components/mega-menu.md
docs/pages/components/tool-bar.md
docs/pages/layouts/global-navigation.md

Closes sap/fundamental#874
mark deprecated components
* http://localhost:4000/layouts/global-navigation.html
* http://localhost:4000/components/mega-menu.html
* http://localhost:4000/components/tag.html
* http://localhost:4000/components/toolbar.html
**New**
nothing 
**Changed**
* docs for deprecated components 
**Removed**
nothing

#874 mark deprecated components

---

docs/pages/components/form.md

Closes sap/fundamental https://github.com/SAP/fundamental/issues/1049
Align inline help to left
* http://localhost:4000/components/form.html

Bugfix/Inline help in form - 1049

---

docs/pages/components/button.md

Closes sap/fundamental https://github.com/SAP/fundamental/issues/1084
Aria attributes added to the markup
*  http://localhost:4000/components/button.html

Update markup for light button in docs

---

docs/index.html

Closes sap/fundamental https://github.com/SAP/fundamental/issues/1085
Update text in Type section in home page of docs website

Update copy in type section

---

test/resources/contexts.js
test/resources/controls.js
test/templates/forms.njk
test/templates/index.njk
test/templates/layout.njk

Some cleanup in the test environment. There are also a few files in /test/resources that probably can be removed. Will look into it later.

Cleanup in test environment

---

docs/pages/components/form.md

Closes sap/fundamental#822
Updated the documentation of form elements
http://localhost:4000/components/form.html
**New**
**Changed**
**Removed**

Docs/Update Forms usage information#822

---

less/fiori-fundamentals-ie11.less
less/fiori-fundamentals.less
scss/components/button.scss

Closes sap/fundamental#1111
Adds missing CSS var fallback values for emphasized button hovers
> NOTE: I compiled the LESS only for testing purposes. The file will be re-generated during the release process.
* Fallback values for color and background color now in `less/fiori-fundamentals-ie11.less` —  https://github.com/SAP/fundamental/compare/feature/1111-emphasized-fallbacks?expand=1#diff-06f46107fdc53b065b9dd5b6cabb0adcR2164
Now has ...
```
.fd-button--emphasized:hover {
--fd-button-background-color: var(--fd-color-action-hover);
--fd-button-color: var(--fd-color-action-2);
color: white;
background-color: #085caf; }
```
**New**
* CSS var fallbacks for emphasized hover states
**Changed**
* Updates button SASS only
**Removed**
* N/A

#1111 adds css var fallbacks for emphasized button hover

---

scss/helpers.scss
scss/helpers/_backgrounds.scss
scss/helpers/_borders.scss
scss/helpers/_colors.scss
scss/helpers/_table.scss
scss/mixins/_vars.scss
test/templates/pages/helpers.njk

Closes sap/fundamental#1128
Implements CSS vars with fallbacks for color helper classes
* http://localhost:3030/pages/helpers
**New**
* New test page for color helpers
**Changed**
* The var color mixin now accepts a 4th param to force an `!important`
**Removed**
* N/A

#1128 css vars for helpers

---

docs/js/customscripts.js

**New**
**Changed**
**Removed**

Hide mobile btn in prod

---

README.md

There is also a Vue implementation of Fundamentals in the works.

adds note about vue implementation

---

scss/components/calendar.scss
test/templates/calendar/data.json

Closes sap/fundamental#1220
Adds `rtl` support to `calendar`
* http://localhost:3030/calendar
**New**
* N/A
**Changed**
* N/A
**Removed**
* N/A

#1220 adds rtl support to calendar

---

scss/components/action-bar.scss
test/templates/action-bar/data.json

Closes sap/fundamental#1218
Add `rtl` support to `action-bar` component
* http://localhost:3030/action-bar
**New**
* N/A
**Changed**
* N/A
**Removed**
* N/A

#1218 adds rtl support to action bar

---

scss/components/menu.scss
test/templates/menu/data.json

Closes sap/fundamental#1223
Add `rtl` support to `menu` component 
* http://localhost:3030/menu
**New**
* N/A
**Changed**
* N/A
**Removed**
* N/A

#1223 adds rtl support for menu

---

scss/components/modal.scss
test/templates/modal/data.json

Closes sap/fundamental#1224
Adds `rtl` support to `modal` component
* http://localhost:3030/modal
**New**
* N/A
**Changed**
* N/A
**Removed**
* N/A

#1224 adds rtl support to modal

---

scss/components/tree.scss
test/templates/tree/component.njk
test/templates/tree/data.json
test/templates/tree/index.njk

Closes sap/fundamental#1232
Adds `rtl` support to `tree` component
* http://localhost:3030/tree
**New**
* N/A
**Changed**
* N/A
**Removed**
* N/A

#1232 adds rtl support to tree

---

scss/components/product-menu.scss
scss/components/search-input.scss
scss/components/shellbar.scss

Closes sap/fundamental#1229
Adds last bit of support for shellbar and its child components.
* http://localhost:3030/shellbar

Adds last bit of RTL support for shellbar

---

scss/components/product-switcher.scss
test/templates/product-switcher/index.njk

Closes sap/fundamental#1228
Small update for RTL support in current iteration of the product-switcher. Bug fix for presentation on the test page.
* http://localhost:3030/product-switcher

Bug fix on test page and RTL support in product-switcher

---

.travis.yml
ci-scripts/publish-rc.sh
ci-scripts/publish.sh
ci-scripts/setup-npm.sh
package-lock.json
package.json
scripts/publish-release.sh

Automated builds, deployment and use semantic versioning.

chore: Automate builds and versioning

---

package.json

license: "ISC" is incorrect. fixing.

chore: update license

---

.travis.yml

remove caching in travis - I need this for a followup pr to renable visual regression testing.

chore: removing caching for travis

---

netlify.toml

Initial netlify changes to prevent failing builds. A follow up in necessary to move the account from @joseegm to @fundamental-bot

chore: initial netlify changes

---

scss/layout/app.scss

fix: #1329 issue of rendering main part as part of Application with Sidebar

---

README.md

chore: #1362 update README.me and documenting what breaking changes are

---

ops/gulp/docs-css.js
scss/_mixins.scss
scss/helpers.scss
scss/helpers/_display.scss
scss/mixins/_breakpoints.scss

fix: restores display helpers with relevant mixins

---

docs/pages/components/identifier.md
scss/components/identifier.scss

fix: Fixes documentation and background bug for identifiers

---

scss/components/popover.scss

In order for the popover to appear when inside a modal, the z-index value needed to be updated.
**Changed**
* Update popover z-index to "top"

fix: Bumped the popover z-index

---

scss/components/table.scss

fix: Removes the opinion of uppercase headers on tables

---

.travis.yml

Update slack notification channel for travis updates.

fix: update slack channel for travis

---

scss/components/table.scss

fix: #1284 remove pointer from the table rows

---

scss/components/dropdown.scss

**Changed**
dropdown.scss
The current modifications fix the issue with the dropdown button mis

fix: dropdown button issue fix

---

scss/core/_forms.scss

fix: Radio component update

---

scss/_settings.scss
scss/core/_forms.scss
scss/core/_root.scss

Closes sap/fundamental#1333
A first pass at fixing some of the references pointing in many different directions for checkboxes (touches shared radio code as well).

fix: Fixes states and references for colors of checkboxes

---

scss/components/table.scss

fix: Updates table header background

---

docs/pages/foundation/colors.html
docs/pages/foundation/spacing.html
docs/pages/resources/design-system-utilities.md
docs/pages/resources/how-to-use-scss.md

Closes sap/fundamental#1295, also addresses issues in sap/fundamental#1432
Fixes incorrect some incorrect links and a typo.

fix: update some links in documentation site

---

docs/pages/components/table.md
scss/components/table.scss
test/templates/table/component.njk
test/templates/table/index.njk

Closes sap/fundamental #1365 
updated component page with scope attributes to <th> and opimized table.scss to support fd-table_fixed-col class to be put on <th> in <tbody> as well.
Also fixes/prepares solution for: https://github.com/SAP/fundamental-vue/issues/242 #242 
**Changed**
* changed fd-table_fixed-col to support <th> as well.

Fix: Restructured .fd-table_fixed-col class

---

scss/layout/_app.scss
scss/layout/_shell.scss

fix: fixes the scrolling issue with the vertical sidenav

---

package-lock.json

tar bug fixes have backported data that node-sass needed in order to function - by updating package-lock we will be compliant again. 
See: https://github.com/sass/node-sass/issues/2625

fix: update tar dependency - node-sass

---

scss/components/breadcrumb.scss

fix: Removed margin bottom

---

docs/pages/components/action-bar.md

Closes sap/fundamental#1360
Added aria-label for action bar mobile view as per issue #1360.

fix: Added aria-label for Action Bar Mobile View

---

scss/components/action-bar.scss

fix: Fixed popover in action bar misaligned with other buttons

---

.github/mergeable.yml

chore: add initial version of mergeable

---

docs/_includes/head.html

fix the path to the doc website

docs: fixs the path that show the doc page

---

.travis.yml

chore: update node version for security fix

chore: update node version for security fix

---

scss/_settings.scss

fix: update accent 10 value

---

.github/mergeable.yml

chore: update mergable.yml file

---

.github/mergeable.yml
ci-scripts/publish-rc.sh
docs/_includes/head.html

chore:test release

---

package-lock.json
package.json

chore: revert standard version

---

.github/mergeable.yml

chore: fix regex in mergeable

---

package-lock.json
package.json

bump some security related libraries

chore: bump some security related libraries

---

.reuse/dep5
LICENSE
LICENSES/MIT.txt
NOTICE
README.md

chore: migrate from CLA to DCO

---

.github/mergeable.yml

chore: update mergeable

---

docs/_config.yml
docs/index.html

chore: fix typo

---

.github/mergeable.yml

chore: replace Gracjan with Jessie and Kasha in mergeable

chore: replace Gracjan with Jessie and Kasha in mergeable

---

README.md

**New**
**Changed**
**Removed**

chore: add REUSE

---

.reuse/dep5
LICENSES/Apache-2.0.txt

**New**
**Changed**
**Removed**

chore: update DCO config

---

docs/_sass/_landingPage.scss
docs/index.html

Closes sap/fundamental#1573
this pr will add the new footer, page and footer at size xl will be targeted in another pr

docs: footer

---

docs/index.html

chore: add netlify banner

---

docs/index.html

chore: update netlify link

---

docs/index.html

chore:fix netlify again

---

docs/_sass/_landingPage.scss

There was typo in documentation page styles

fix: Correct typo

---

.github/mergeable.yml

chore: update mergeable.yaml

---

scss/_settings.scss

Some invalid scss instructions

fix: Compilation issues

---

docs/index.html

add relative path to the conf banners images

docs: add relative path to the conf banners images

---

package-lock.json
package.json

Added missing package `conventional-changelog-cli`

chore: add conventional-changelog-cli

---

ci-scripts/publish-rc.sh
ci-scripts/publish.sh
package-lock.json
package.json

chore: update bump version

---

.github/in-solidarity.yml

add in-solidarity to check inclusive language

chore(deps-dev): add in-solidarity to check inclusice language

---

.github/in-solidarity.yml

update in-solidarity.yml configuration

chore(deps-dev): update in-solidarity.yml configuration

---

docs/_sass/_landingPage.scss
docs/index.html

Remove 'Design' section from homepage. 
Update information to include Core and Platform.

chore: update homepage

---

docs/index.html

On the banners, add link to landing page.

chore: add link to landing page

---

docs/index.html

remove the link to the conf page

docs(styles): remove the link to the conf page

---

docs/robot.txt

add robot.txt to exclude it from search

chore: add robot.txt to exclude it from search

---

docs/index.html

add link to fundamentalconf.com

fix: add link to fundamentalconf.com

---

netlify.toml
src/index.html

chore: netlify build

---

netlify.toml

update netlify node version 18.18.2

chore: update netlify node version 18.18.2

---

angular.json
package-lock.json
package.json

chore: migrate to angular 17

---

package-lock.json
package.json

update ghpages package version 1.0.7

chore: update ghpages package version 1.0.7

---

package.json

chore: add deploy command

---

src/app/fl-footer/fl-footer.component.html

docs: remove twitter link

---

src/app/app.component.scss
src/app/fl-card/fl-card.component.scss
src/app/fl-conference/fl-conference.component.scss
src/app/fl-design/fl-design.component.scss
src/app/fl-footer/fl-footer.component.html
src/app/fl-footer/fl-footer.component.scss
src/app/fl-intro/fl-intro.component.scss
src/app/fl-purpose/fl-purpose.component.scss
src/app/fl-used/fl-used.component.scss
src/styles.scss

**New**
**Changed**
**Removed**

chore:  Fundamental Website

---

.github/workflows/gh-pages-deploy.yml

Introduce ghpage deploy action in merge

chore: gh-pages-deploy.yml

---

src/app/fl-card/fl-card.component.scss

fix: shadow

---

src/index.html

Fixing the reference link for the fundamental library wesite.

fix: reference link

---

package.json

test: deploy with param

---

.github/workflows/gh-pages-deploy.yml

chore: simplify deploy action

---

.github/workflows/gh-pages-deploy.yml

chore: revert page action

---

.github/workflows/gh-pages-deploy.yml

chore(ci): update ghaction versions

---

src/app/fl-conference/fl-conference.component.html

docs: update conf link
