SAP/fundamental

.gitignore, docs/_data/sidebars/left-navigation-sidebar.yml, docs/css/fundamental-ui.css
this change ensures that docs/css/fundamtental-ui.css is copied over to _site on jekyll build as the stand alone file is required by the starter pages.
=> #57 removing css/fundamental-ui.css from gitignore.

scss/components/alert.scss, scss/icons/_mixins.scss, scss/icons/icon.scss, test/templates/alert/component.njk, test/templates/alert/data.json, test/templates/alert/index.njk
#201 
Matches https://zpl.io/2poQdgl
- Adds `--dismissible` modifier to prevent content wrapping around the close button (this class modified is **required** now)
- Improved the icons mixins so you can use `@include fd-icon("decline", "l")`and it will add all the relevant styles needed meaning you don't need to use an empty icon span. See [this](https://github.com/SAP/fundamental/pull/218/files#diff-d7fd5b7374da98196ff1a3e856af6cf5R38).
=> #201 updates alert, improves icons mixins

scss/components/modal.scss, scss/layout/overlay.scss, test/templates/index.njk, test/templates/modal/component.njk, test/templates/modal/index.njk, test/templates/pages/overlay.njk
#204 
- Markup for the `footer` changed — the element class is now `__footer` and added an `actions` container
- Added an example page using the `.ui__overlay` and `.fd-overlay` components at http://localhost:3030/pages/overlay
=> #204 updates modal, add overlay example page

scss/components.scss, scss/components/button-group.scss, scss/components/button.scss, scss/mixins/_mixins.scss, test/templates/button-group/component.njk, test/templates/button-group/data.json, test/templates/button-group/index.njk, test/templates/index.njk
#193
localhost:3030/button-group
Not a perfect match to the design. I retained the borders for the `pressed` state since it's tricky to rain the exact size but remove adjacent borders. Not impossible but we can circle back and do it later.
=> #193 introduces button-group component

scss/components/inline-help.scss, scss/components/tree.scss
#202 
Updated component - http://localhost:3030/inline-help
Design specs - https://zpl.io/agnkooZ
The design for the popover was applied. A slight variation on the box-shadow effect. Since we have to account for a triangle with the popover, box-shadow cannot be used. The filter(drop-shadow( ... )) is used instead and it does not support multiple layers like box-shadow, but it's close enough to the design.
=> #202 style updates to inline help popup

docs/_data/components.yml, docs/_data/sidebars/left-navigation-sidebar.yml, docs/_includes/search-box.html, docs/pages/components/card-group.md, docs/pages/components/card.md, docs/pages/components/tool-bar.md
just need to verify that the card, card-group and toolbar pages are not visible on the site.
=> #270 hide cards, card-group and toolbar pages

scss/components/badge.scss
#499 
changed font size to 10.99px which is what fd-type(-3) renders. it's not 11px shown in the design sheet, but close enough and adheres to the type system.
=> #499 change font size from fd-type(-2) to -3

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .npmignore
Closes sap/fundamental#468
Adds simple issue and PR templates to collect better information from requestors and get better info for change logs, respectively.
* After merge, create a new issue and a PR
**New**
* Adds `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md` to activate Github template functionality
**Changed**
* Nothing 
**Removed**
* Nothing
=> #468 inital addition of issue templates

test/templates/modal/component.njk, test/templates/modal/index.njk
Closes sap/fundamental#502
Updates the primary action button and the close button in the modal
http://localhost:3030/modal
* The close button should now act like a `--secondary` button, blue with `hover` and `pressed` states
* The affirmative action in the footer should be a `--primary` button, outlined instead of filled.
**New**
* Close button receives an additional class `fd-button--secondary`
```
<button class="fd-button--secondary fd-modal__close"></button>
```
**Changed**
* The affirmative action button changes to class `fd-button--primary`
```
<button class="fd-button--primary">Confirm</button>
```
**Removed**
* Nothing
=> #502 fixes primary action and changes close button

ops/gulp/docs-build.js, ops/gulp/docs-fonts.js
small fix.
404 for 42 fonts in docs.
All Examples use font 'arial'
Manual
It takes time to update (In my forks it took 1 hour). I think github page cache 404.
**New**
gulp task for copy fonts.
=> fix fonts problem in docs

scss/components/global-nav.scss, test/templates/global-nav/component.njk, test/templates/global-nav/index.njk, test/templates/pages/all.njk, test/templates/pages/panel.njk, test/templates/toolbar/component.njk, test/templates/toolbar/index.njk
Closes sap/fundamental#526
Fixes broken test pages after dropdown/menu/popover refactor
* http://localhost:3030/action-bar
* http://localhost:3030/global-nav
* http://localhost:3030/pages/panel
* http://localhost:3030/pages/all
**New**
nothing
**Changed**
* http://localhost:3030/action-bar
* http://localhost:3030/global-nav
* http://localhost:3030/pages/panel
* http://localhost:3030/pages/all
**Removed**
nothing.
=> Fix broken test pages after menu/popover refactor

scss/components/side-nav.scss, scss/layout/app.scss, scss/layout/ui.scss
Closes #552, #553
scss updated in app.scss to remove unnecessary verticle and horizontal scrolling at app level. 
* open http://localhost:3030/pages/app/sidebar - verify that there are no scrollbars. 
**New**
* nothing
**Changed**
* Width of `side-nav` to 249px. this eliminates a horizontal scroll when side-nav is placed within `side-nav`
* Reduced 100vh on 100vh - 50px to account for the app header height 
* Changed scrolling from `scroll` to `auto` on `app__main` and `app__sidebar`
**Removed**
* nothing
=> #552 scss updates to remove unnecessary scrolling on apps layout

test/templates/menu/component.njk, test/templates/popover/component.njk
Closes sap/fundamental#543
Adds a closing `ul` to the `menu` component.
* http://localhost:3030/contextual-menu
* http://localhost:3030/menu
Now has closing `ul`
```
<nav class="fd-menu">
<ul class="fd-menu__list">
<li><a href="#" class="fd-menu__item">Option 1</a></li>
<li><a href="#" class="fd-menu__item">Option 2</a></li>
<li><a href="#" class="fd-menu__item">Option 3</a></li>
<li><a href="#" class="fd-menu__item">Option 4</a></li>
</ul>
</nav>
```
**Changed**
* Applies to test environment only.
=> #543 adds closing ul to menu

ops/gulp/docs-build.js, ops/gulp/docs-icons-theme-ariba.js, ops/gulp/pkg-build.js, ops/gulp/pkg-css-theme-ariba.js, ops/gulp/pkg-icons-ariba.js
- Add new icon & css task for Ariba-Theme
- Update create task to run Ariba-Theme gulp task
* Included in standard gulp job to produce new Ariba-Theme artifacts.
**New**
* Add Gulp task to generate Ariba Theme Font Icon and CSS files
**Changed**
* Update Gulp task to run Ariba Theme related jobs
**Removed**
* None
=> Update gulp packaging task for Ariba Theme

docs/_includes/side-nav.html, docs/scss/_docs-side-nav.scss
- Update side-nav css to show & indent 3rd level menu item properly.
- Update doc side menu rendering to apply right css and to show 3rd level only when respective header is selected.
* Test with up coming Ariba-Theme 3rd-level menu items
**New**
* None
**Changed**
* Side-Nav CSS update to indent & show correctly.
* Update Doc Side-Nav rendering to 3rd level item links and display children only when parent is selected.
**Removed**
* None
=> Update doc side navigation for 3rd level menu item

scss/_settings.scss, scss/core/root.scss, scss/layout/_mixins.scss, scss/layout/container.scss, scss/layout/page.scss, scss/layout/section.scss, test/templates/index.njk, test/templates/pages/grid.njk, test/templates/pages/layouts/page.njk
Closes sap/fundamental#366
Implements variable `section` padding and `col` gutters based on screen size
|breakpoint|ui padding|gutter|
|--|--|--|
| default | 8px | 8px |
| xs (320) |  | |
| s (800) | 12px | 8px |
| m (1024)  | 16px | 12px |
| l (1440)  | 32px | 16px |
| xl (1580) | | |
* http://localhost:3030/pages/grid
* http://localhost:3030/layout
> NOTE: IE 11 will always use the `l` SASS value. All other modern browsers will use the CSS var values.
**New**
* Padding and gutter values added to `root` scss
* Page and section containers updated to use CSS vars with fallback
* Flow mixin updated to use CSS vars with fallback
**Changed**
* Default `$fd-padding--ui` and `$fd-width--gutter` updated to new values
**Removed**
* Deleted CSS for deprecated `.fd-page__intro` container
=> #366 css vars for padding and gutters

scss/theme/ariba/icons/icon.scss
Add RTL support for SAP-Icons under Ariba-Theme
* Documentation
**New**
* None
**Changed**
* Ariba-theme "icons.scss", add class for SAP-Icon under RTL.
**Removed**
* None
=> Update Ariba-Theme Add SAP-Icon RTL support.

package-lock.json, package.json
Closes sap/fundamental#591
`package.json` updates that are accomplished with an `npm audit fix`. Running the command with the `-force` flag will update gulp to 4.0 and cause a couple issues due to how our tasks are written. Currently, 4.0 is the "next" release for gulp and not out as an official/stable version. 
Current audit status: `found 74 vulnerabilities (27 low, 35 moderate, 12 high) in 16621 scanned package`
=> bug/591 - npm audit fix

README.md
Closes sap/fundamental# N/A
Correct the spelling of Xcode and macOS in the readme.
N/A
N/A
**Changed**
Spelling in Readme.
=> Correct macOS and Xcode related spellings

scss/layout/col.scss
Closes sap/fundamental#838
At some point the stacking behavior of the columns at small screens was reverted. 
* http://localhost:3030/pages/grid
**New**
* None
**Changed**
* The `col` containers go full width below the `m` breakpoint
**Removed**
* None
=> #838 fixing col stacking

docs/_data/colors.yml, docs/_includes/colors.html, test/templates/pages/styles.njk
Closes sap/fundamental#843
Update colors documentation page to match design system colors 
* http://localhost:4000/foundation/colors.html (updated page) 
* http://localhost:3030/pages/styles (reference for colors) 
**New**
nothing 
**Changed**
* updated colors to match design system colors 
**Removed**
* Removed `fd-color` function documentation in favor of css vars
=> #843 update colors documentation page to reflect color palette

scss/components/breadcrumb.scss
Closes sap/fundamental https://github.com/SAP/fundamental/issues/853
Remove top padding from breadcrumb
* http://localhost:3030/breadcrumb
=> Bugfix/remove padding on breadcrumb #853

scss/components/status-label.scss
Closes sap/fundamental# https://github.com/SAP/fundamental/issues/851
Moves the associated status label icon up to be better aligned with the status label text.
* http://localhost:3030/status-label
Before:
Now:
=> Fix vertical alignment in status label.

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATES/BUG_REPORT.md, .github/ISSUE_TEMPLATES/COMPONENT_REQUEST.md, .github/ISSUE_TEMPLATES/FEATURE_REQUEST.md
> The CONTRIBUTING file can be updated easily but the issue templates are only being committed so that the admin can apply them in the Settings once we agree they are OK.
sap/fundamental#902
Adds new issue templates. This alone will not close this. Once reviewed and merged, the Github admin will need to put these into action in Settings.
https://help.github.com/articles/creating-issue-templates-for-your-repository/
* Once completed by the admin, when clicking on New Issue an interstitial page will appear with the three choices.
**New**
* Adds New Component, Bug Report, and Feature Request templates.
=> #902 new issue templates

scss/functions/_type.scss
Closes sap/fundamental https://github.com/SAP/fundamental/issues/802
The issue was that in @warn we were passing a variable that didn't exist.
* http://localhost:3030
=> Error handling of type functions

CODE_OF_CONDUCT.md
We don't have a code of contact so adding at least the githubs default one is a good start. Please review.
=> Add code of conduct for contributors

scss/components/input-group.scss
Closes sap/fundamental# https://github.com/SAP/fundamental/issues/790
Added RTL style for input-group
* http://localhost:3030/input-group
* http://localhost:3030/localization-editor
Now:
And:
=> Adding input-group RTL support

docs/pages/components/tabs.md, docs/scss/_docs-display-component.scss, scss/components/tabs.scss, test/templates/tabs/index.njk
Closes sap/fundamental#846
Updated tabs style to match [new specs](https://github.com/SAP/fundamental/issues/846).
* http://localhost:3030/tabs
* http://localhost:4000/components/tabs.html
**Changed**
* Tabs default state colors 
* Tabs Active state colors 
* active state border width 
* white background color by default 
before: 
after:
=> #846 Update tabs styles per new specs

docs/scss/_docs-display-component.scss
Closes sap/fundamental https://github.com/SAP/fundamental/issues/592
I tested the tree, the menu and the popover and I think this was more a docs website bug because of some css rules from the parent. 
* http://localhost:4000/components/tree.html
Before:
After:
=> Bugfix/text alignment in tree - #592

docs/.gitignore, docs/_config.yml, docs/gulpfile.js, docs/package.json, netlify.toml
Closes sap/fundamental# https://github.com/SAP/fundamental/issues/946
Adds gulp tasks and node environment to Netlify build.  In order for the Netlify build to detect node, the base directory (docs) needs to have a package.json.  I've introduced a blank one to the docs directory, and install the correct root package.json at runtime. Similarly, the base directory needs a gulp file to run the associated gulp tasks.
The ideal scenario might be to look at hosting this (and the test site) with node rather than using Jekyll and remove this duplication.
* Validate that the Netlify built site has the CSS applied.
**New**
* Added gulp/NPM support into Netlify build
=> Adding support for gulp tasks with netlify

scss/components/form.scss, scss/components/popover.scss, scss/components/tag.scss, scss/layout/col.scss, scss/layout/page.scss, test/templates/pages/floorplans/object.njk, test/templates/pages/layouts/page.njk
Closes sap/fundamental#1006
This adds a spec floorplan page for testing purposes.
* localhost:3030/pages/floorplans/object
**New**
* Test Object page
**Changed**
* Several small spacing updates were made to comply with Fiori 3.0 specs
* Adds `is_object_page` template var which enables a white background behind the `page__header` container
**Removed**
* N/A
=> #1006 adds a spec object page

docs/pages/components/table.md, scss/components/table.scss, test/templates/table/component.njk, test/templates/table/index.njk
Closes sap/fundamental#807
Add neutral borders and Zebra stripping to Tables
http://localhost:4000/components/table.html
http://localhost:3030/table
**New**
.fd-table--no-borders td {
border-bottom: none;
}
.fd-table--striped tr:nth-child(even) {
background-color: fd-color-state("hover");
}
=> Feature/Add remover lines#807

docs/pages/components/tabs.md
Closes sap/fundamental#220
Update tabs docs page with an example of overflow tabs using popover menu.
* http://localhost:4000/components/tabs.html
**New**
nothing 
**Changed**
* tabs docs - added overflow menu examples 
**Removed**
nothing
=> #220 add overflow menu example to tabs docs

docs/pages/foundation/index.md
Closes sap/fundamental#1072
Removes Designer and Developer Getting Started links from the [Foundation page](https://sap.github.io/fundamental/foundation/index.html). The dev link is broken and the design page is not useful.
* http://localhost:4000/foundation/index.html
**New**
* N/A
**Changed**
* N/A
**Removed**
* Removes links from Foundation page
=> #1072 removes links from Foundation page

docs/pages/foundation/grid.html, scss/_settings.scss, scss/core/root.scss, test/templates/pages/grid.njk, test/templates/pages/styles.njk
Closes sap/fundamental#1042
Updates breakpoints and UI side padding slightly to conform with approve specs. **This only changes side padding and gutters, inner content padding and bottom margins will be addressed later.**
> Note: The `s` breakpoint of `320` is retained since it can be useful but it is not a specific breakpoint in terms of the design system and is not documented.
* http://localhost:3030/pages/grid
* localhost:4000/foundation/grid.html
**New**
* N/A
**Changed**
* Breakpoint `l` now starts at `1024px`, `xl` now starts `1441`, and `xxl` now `>1920`
* Side padding for high level containers like `shellbar` and `section`s now use 32px starting at `l`
* Gutters are now 16px for `xl` and `xxl` sizes
**Removed**
* N/A
=> #1042 updates breakpoints and UI padding

scss/_settings.scss, scss/components/input-group.scss, scss/components/modal.scss, scss/components/product-menu.scss, scss/components/table.scss, scss/components/tree.scss, scss/core/forms.scss, scss/mixins/_forms.scss, scss/theme/fundamental.scss
Closes sap/fundamental#1032
Many of the CSS vars for spacing did not have fallback values so they displayed incorrectly on IE11.
> Note: The gutters in IE11 will not vary based on breakpoints. They will always display with the desktop default of 16px.
Enable fallbacks by setting `$fd-support-css-var-fallback: true` before testing in IE11.
* http://localhost:3030/forms input and select heights
* http://localhost:3030/product-menu height
* http://localhost:3030/input-group height for default and compact
* http://localhost:3030/modal padding around modal containers
* http://localhost:3030/table cell padding
* http://localhost:3030/tree row and cell padding
**New**
* Adds default for `$fd-width--gutter` 
* Deprecates `$fd-forms-height--input-text` in favor of the base `$fd-forms-height` …
=> #1032 adds fallback options for size CSS vars

docs/pages/guides/how-to-use-scss.md
Closes sap/fundamental https://github.com/SAP/fundamental/issues/1017
Add in docs that $fd-fonts-path needs to be specified otherwise it causes a compilation error.
=> Update how to use scss guide - 1017

scss/components/button.scss, scss/components/shellbar.scss, scss/core/elements.scss, scss/mixins/_mixins.scss, scss/mixins/_states.scss
Closes sap/fundamental#1054
Removes `pressed` and `active` selectors from the `fd-selected` mixin, implements new combo mixin `fd-active-pressed-selected`
* http://localhost:3030/table
**New**
* Use the combo mixin `fd-active-pressed-selected` for buttons and elements that can have multiple states but with the same styling
* The `fd-selected` can be used for table rows and list items that only need to support the `selected` state
**Changed**
* Fixes bug with table row states
**Removed**
* N/A
=> #1054 confines fd-selected mixin, adds combo state mixins

scss/helpers.scss, scss/helpers/_display.scss, scss/helpers/_flex.scss, scss/helpers/_general.scss, scss/helpers/_grid.scss, scss/helpers/_layout.scss, scss/helpers/_type.scss
Closes sap/fundamental#1099
Reorganizes some helper classes into more logical groupings, deprecates the `general` helper file in favor of more specific groups.
> NOTE: Anyone using individual `helpers` as imports may encounter issues. It is recommended you update your imports or use the entire `helpers.scss` file instead.
* Distributed helpers file should include the full set of helpers as before
**New**
* Breakpoint display classes use the format `fd-had-display-none--m` and follow a mobile-first approach meaning this class would show the element at `xs` and `s` screens but hide it starting at `m` and above.
* Expands `flex.scss` `align-items` helpers
* Expands `display.scss` helpers to include all display types for breakpoints
**Changed**
* Removes `general` SASS file from `helpers` …
=> #1099 moves some helper classes to more logical sass files

scss/layout/app.scss, scss/layout/overlay.scss, scss/layout/page.scss, scss/layout/panel-grid.scss, scss/layout/panel.scss, scss/layout/section.scss, scss/layout/shell.scss
Closes sap/fundamental#1122
Implements CSS vars with fallbacks for layout modules
There should be no discernable visual changes.
* http://localhost:3030/pages/shell
* http://localhost:3030/pages/app
* http://localhost:3030/pages/modal-placement
* http://localhost:3030/pages/page
* http://localhost:3030/pages/section
* http://localhost:3030/pages/page
* http://localhost:3030/panel
* http://localhost:3030/panel-grid
**New**
* N/A
**Changed**
* To enable the fallbacks, the flag `$fd-support-css-var-fallback` must be set to true in a custom SASS build.
**Removed**
* N/A
=> #1122 implements CSS vars with fallbacks for layout modules

test/app.js
Closes sap/fundamental#1140
Removes reference to deprecated `toolbar` data file.
* Startup app with `npm test` should not throw an error
* Viewing test pages should not throw an error 
**New**
* N/A
**Changed**
* N/A
**Removed**
* Removed `toolbar` data file from `app.js`
=> #1140 fixes missing data file error

scss/components/badge.scss, scss/components/counter.scss, scss/components/identifier.scss, scss/components/inline-help.scss, scss/components/label.scss, scss/components/popover.scss, scss/components/product-menu.scss, scss/components/spinner.scss, scss/components/status-label.scss, scss/components/token.scss, scss/mixins/_mixins.scss, test/templates/badge/data.json, test/templates/badge/index.njk, test/templates/counter/data.json, test/templates/counter/index.njk, test/templates/identifier/data.json, test/templates/image/data.json, test/templates/inline-help/data.json, test/templates/inline-help/index.njk, test/templates/label/data.json, test/templates/label/index.njk, test/templates/spinner/data.json, test/templates/spinner/index.njk, test/templates/status-label/data.json, test/templates/status-label/index.njk, test/templates/token/data.json, test/templates/token/index.njk
Closes sap/fundamental#1126
Implements CSS vars with fallbacks for indicators
There should be no discernable visual changes.
* http://localhost:3030/badge
* http://localhost:3030/identifier
* http://localhost:3030/inline-help
* http://localhost:3030/label
* http://localhost:3030/spinner
* http://localhost:3030/status-label 
* http://localhost:3030/token
* http://localhost:3030/counter
Affected by refactoring of the triangle mixin.
* http://localhost:3030/product-menu
* http://localhost:3030/popover
**New**
* The triangle mixin now accepts a fourth param for a CSS var which is the foreground color. The refactoring only handles foreground color and only for `up`, `down`, `left` and `right` since those are the only combinations used. 
**Changed**
* To enable the fallbacks, the flag …
=> #1126 updates css vars for indicators

scss/components/action-bar.scss, scss/components/modal.scss, scss/components/product-switcher.scss, scss/components/shellbar.scss, test/templates/action-bar/data.json, test/templates/modal/data.json, test/templates/modal/index.njk, test/templates/product-menu/data.json, test/templates/product-menu/index.njk, test/templates/product-switcher/data.json, test/templates/product-switcher/index.njk, test/templates/shellbar/data.json, test/templates/shellbar/index.njk, test/templates/user-menu/data.json, test/templates/user-menu/index.njk
Closes sap/fundamental#1124
Implements CSS vars with fallbacks for shell and floorplan components
There should be no discernable visual changes.
* http://localhost:3030/action-bar
* http://localhost:3030/modal
* http://localhost:3030/product-menu
* http://localhost:3030/product-switcher
* http://localhost:3030/shellbar
* http://localhost:3030/user-menu
**New**
* N/A
**Changed**
* To enable the fallbacks, the flag `$fd-support-css-var-fallback` must be set to `true` in a custom SASS build.
**Removed**
* N/A
=> #1124 shellbar components css vars

docs/_data/colors.yml, docs/_data/versions.yml, scss/_settings.scss, scss/components/alert.scss, scss/components/token.scss, scss/core/root.scss, test/templates/pages/styles.njk
Closes sap/fundamental#1214
Fixes alert transparency bug by adding semantic background colors to the background colors map. These values are no longer calculated based on the status colors and must be managed when theming.
* http://localhost:3030/pages/styles
* http://localhost:4000/foundation/colors.html
* http://localhost:3030/alert
* http://localhost:3030/token
**New**
* `$fd-colors` map now has status backgrounds as shades 3-6.
* CSS var `--fd-color-background-information` now available
**Changed**
* `alert--information` and `token` now use `information` background instead of `selected` state
**Removed**
* Status backgrounds are no longer listed under state colors but the state color function, e.g., `fd-color-state("positive")`, still works as before
=> #1214 adds new background colors for semantic colors

scss/layout/panel.scss, test/templates/panel/data.json
Closes sap/fundamental#1227
Adds `rtl` support to `panel` layout component
> NOTE: I'm not sure why the class name is wrapping in Chrome but actual content seems to work OK
* http://localhost:3030/panel
* http://localhost:3030/pages/panel
* http://localhost:3030/panel-grid
**New**
* N/A
**Changed**
* N/A
**Removed**
* N/A
=> #1227 add rtl support to panel

scss/components/inline-help.scss, test/templates/inline-help/data.json
Closes sap/fundamental#1221
Adds `rtl` support to `inline-help` component
> NOTE: Consider renaming these in the future to use `before` and `after` instead of directional names, e.g., `bottom-after`. Generally, also, the names are a bit confusing since they refer to the placement of the container and not the arrow.
* http://localhost:3030/inline-help
**New**
* N/A
**Changed**
* N/A
**Removed**
* N/A
=> #1221-rtl-help adds rtl support for inline-help

scss/components/nav.scss, scss/core/elements.scss, test/templates/nav/data.json
Closes sap/fundamental#1225
Updates `ol, ul` padding to `0` all around to fix `rtl` start indentation
* http://localhost:3030/nav
**New**
* N/A
**Changed**
* N/A
**Removed**
* N/A
=> #1225 removes default padding from ul which was affecting rtl mode

docs/pages/foundation/index.md
Because "unified" has a consonant sound, the article to be used in front of it is "a".
Here are a few articles that, taken together, can explain this in more detail.
https://www.merriam-webster.com/words-at-play/is-it-a-or-an
https://en.oxforddictionaries.com/explore/is-the-letter-y-a-vowel-or-a-consonant/
**New**
**Changed**
**Removed**
=> Use "a" for words that start with a consonant sound

docs/pages/layouts/panel.md
Fixes sap/fundamental #1290 
The CSS class `fd-panel__content` appears to have been replaced by `fd-panel__body`.
=> fix: Update docs for Panel elements

.stylelintrc.yml, scss/components/button.scss, scss/components/calendar.scss, scss/components/dropdown.scss, scss/components/spinner.scss
reorg stylelintrc.yml to match https://stylelint.io/user-guide/rules/ a bit closer.
enable rule:  no-duplicate-selectors
skip no-duplicate-selectors, button.scss - seems to have been called out as to be deprecated.
=> fix: no-duplicate-selectors

package-lock.json
A bad version of remark-parse was checked in in the package-lock file. This is causing failures on npm install inside of Travis.
=> chore: bad package-lock is causing travis failures

docs/_data/versions.yml, docs/_includes/status-container.html, docs/css/fui-site.css, docs/pages/components/index.html, docs/scss/_docs-general.scss
As a result of some confusion around the messaging of the status of components, this removes status labels on individual component pages and adds messaging to the component landing page explaining that there will be additional communication coming.
=> docs: removes status labels and adds alert messaging on landing

netlify.toml, package.json
The netlify config was missing a step that generated the `_config-library.yml` file. 
See error here:
Logs for previews can be accessed via this link: https://app.netlify.com/sites/sad-jones-0308ea/deploys
=> chore: add missing script netlify script

scss/components/popover.scss, scss/core/forms.scss
fixes #1328 
add missing trailing space. found one other instance, and fixed there as well.
unable to locate a lint-rule to cover this.
=> fix: add trailing semi's

package.json
Docs site is currently missing version number.
Travis was not running the `postinstall` script as expected. This pr explicitly adds it to the `build-docs` script so that Travis will run it.
After running new `build-docs` script:
=> fix: modify build-doc script

docs/pages/components/popover.md, scss/components/popover.scss, scss/components/time-picker.scss, test/templates/popover/component.njk, test/templates/popover/index.njk
Added styles specific to a custom implementation of popovers using [popper.js](https://github.com/FezVrasta/popper.js).
**New**
* Added `fd-popover__popper` styles.
=> feat: Popover popper styles

scss/components/time-picker.scss
The styling for the `TimePicker` overlay was missing padding because popper.js places the markup in a different DOM node so the styles needed to be adjusted.
**Changed**
* Altered the selector for adding padding in the popover for `TimePicker`
=> fix: Small refactor for TimePicker using popper

ci-scripts/publish.sh, package-lock.json, package.json
It was found that the calls to GitHub API to build the release notes _could_ happen prior to the commits being pushed (or updated within GitHub).  To help ensure this works, I have moved the create release call below publish.
Also, updated to a new version of `github-assistant` that will include a "Documentation" section in the release notes.
=> chore: Release notes

.stylelintrc.yml, scss/components/shellbar.scss, scss/mixins/_mixins.scss
`shellbar.scss` had a small typo on line 161. Visually verified that everything looks fine on the shellbar playground pages.
=> fix: remove typo from shellbar

scss/components/tree.scss
Closes sap/fundamental#1277
Increases focus area by changing margin, width, and height for chevron button.
*Of note: The size of focus area now matches the dimensions of the ellipsis button on the right.
*Before:*
*After:*
=> Fix: Increased focus ring for chevron button on tree component

scss/components/button.scss
Reverts a small change from https://github.com/SAP/fundamental/pull/1383
The `a.#{$block},` modifier was disallowing consumer overrides for styling on the button component when used as an anchor.
BEFORE:
AFTER:
I know this changed stemmed from https://github.com/SAP/fundamental/issues/1252, but the playground page for this still looks correct to me as long as we keep `a[class*="#{$block}--"]` :
=> fix: remove anchor modifier

scss/components/popover.scss, test/templates/popover/component.njk
If using the default popper.js library, the attributes that get output are `x-placement` and `x-out-of-boundaries` so we are changing the styles to match that.  The react and vue libraries will need to make small changes, but this change needs to occur first.
Although this is _technically_ a breaking change, the only consumers of these styles are the three functional libraries (ngx, react and vue). `fundamental-ngx` hasn't implemented yet so there is no change needed.  `fundamental-react` and `fundamental-vue` have agreed to make their small changes once this is released.
**Changed**
* Changed popover popper attributes
=> fix: Changed popper attributes to match default popper.js

scss/_settings.scss, scss/components/token.scss
Closes sap/fundamental#952
Updated token component to match the latest designs 
before:
after: 
* http://localhost:3030/token
* http://localhost:4000/components/token.html
**New**
nothing
**Changed**
* updated bg color to `neutral 1`
* updated border color from `transparent` to `neutral 3`
* change close icon from `sys-cancel` to `decline`
**Removed**
nothing
=> fix: Update token to new design

docs/pages/components/alert.md, docs/pages/components/modal.md
Closes sap/fundamental#1425
Updates links in Alert and Modal to correct link, adds `site.baseUrl` where missing.
=> fix: update broken links in alert and modal

README.md
Wiki pages were condensed/updated and the links in the readme were not updated.
The icon workflow wiki page has been removed from the readme link, but is still in the wiki. This page needs to be updated with the current workflow, but I'm not sure what that is.
=> fix: readme links now point to updated wiki pages

scss/components/table.scss
Closes sap/fundamental#1445
Long strings in table cells should break-word so they wrap
=> table cells should break-word

package-lock.json, package.json
The `fundamental` repo has been failing when `github-assistant` is attempting to gather the release notes, whereas other repos are working correctly.  The issue is that tag that the script parses from `standard-version`'s output was missing the tag prefix.  The line highlighted in the screenshot should say "tagging release v1.5.8" -- it was missing the "v" prefix so the `github-assistant` code was actually creating a new tag for the version without the "v" prefix and tying the release to that.
Looking through the change log for `standard-version`, this appears to have been fixed in version 4.4.0 (see https://github.com/conventional-changelog/standard-version/commit/b4ed4f9).
=> fix: Bumped standard-version to 4.4.0 to fix issue with the tag prefix

package-lock.json, package.json
In an effort to fix builds on `master`, I am upgrading to standard-version 6.0.1.  If this doesn't work, we will go back to 4.2.0 and just do release notes manually.
=> chore: Upgraded standard-version to 6.0.1

CHANGELOG.md, package-lock.json, package.json
Unable to determine why standard-version 4.4.0 and 6.0.1 don't work -- reverting back to 4.2.0 and release notes will need to be done manually.
=> chore: Reverting back to version 4.2.0 of standard-version

ci-scripts/publish.sh
Since we have been having issues upgrading standard-version, let's add a check to make sure the release tag has the "v" prefix.  This will allow the release to be created properly and contain the automated release notes.
=> chore: Fix up release tag so releases work properly

docs/_includes/search-box.html, docs/js/search.json
Closes sap/fundamental#1476
Removing the `summary` parameter from `search.json` template. it was rendering invalid JSON on the live documentation. oddly enough, the template works fine locally. There is no way to test and see if this fix will work, unless the PR is merged.
=> chore: remove summary from search json template

package.json
update standard version and commit message
`-m` or `--message` is deprecated https://github.com/conventional-changelog/standard-version/blob/master/command.js#L33
Instead of using `%s` we can use `{{currentTag}}` -- https://github.com/conventional-changelog/standard-version/blob/ae032bfa9268a0a14351b0d78b6deedee7891e3a/test.js#L1244
=> chore: update standard version and commit message

docs/_sass/_landingPage.scss, docs/index.html
Fixes the padding on the landing page for tablet sizes
=> docs: tablet mode paddings

docs/_sass/_landingPage.scss, docs/index.html
Closes sap/fundamental#1570
Adds a call to action for the landing page
=> docs: add new call to action

scss/layout/_mixins.scss
There was syntax error causing `dart-sass` fail
=> fix: Compilation typo error 

LICENSE
In order to be able to identify the main license of all managed repositories centrally, the SAP Open Source Program Office (OSPO) asks all teams to have an identifiable license in their repositories. For some reason (probably formatting - we usually have these issues with licenses copied via the [REUSE tool](https://reuse.software)) the [license in this repository is not detected properly by GitHub](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#detecting-a-license). This PR includes text from a [GitHub license template](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) that should facilitate the automated license detection. …
=> chore: Use GitHub license template
